/*
 * gesparadas.java
 *
 * Created on 27 de abril de 2007, 1:14
 */

package Metropolitano;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author  Antonio
 */
public class gesparadas extends javax.swing.JFrame {
    private Grafo grafo;
    /** Creates new form gesparadas */
    public gesparadas(Grafo grafo) {
        initComponents();
        this.grafo=grafo;
        String Sestaciones[] = new String[grafo.thCodigos.size()];
        for(int i=0; i<grafo.thCodigos.size();i++){
            Sestaciones[i] = (String)grafo.thCodigos.get(i);            
        }
        jComboBox1.setModel(new DefaultComboBoxModel(Sestaciones));        
        String estacion = (String)jComboBox1.getSelectedItem();
        int est = (Integer)grafo.thEstaciones.get(estacion);
        if (grafo.desactivadas[est]){
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(true);
        }
        else{
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(false);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDesktopPane1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gesti\u00f3n de paradas");
        jLabel1.setBounds(140, 50, 130, 14);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCheckBox1.setBackground(new java.awt.Color(51, 102, 255));
        jCheckBox1.setText("Activar");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox1.setBounds(240, 90, 110, 15);
        jDesktopPane1.add(jCheckBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCheckBox2.setBackground(new java.awt.Color(51, 102, 255));
        jCheckBox2.setText("Desactivar");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckBox2.setBounds(240, 140, 130, 15);
        jDesktopPane1.add(jCheckBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton1.setBounds(180, 200, 80, 23);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox1.setBounds(70, 120, 110, 22);
        jDesktopPane1.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String estacion = (String)jComboBox1.getSelectedItem();
        int est = (Integer)grafo.thEstaciones.get(estacion);
        if (grafo.desactivadas[est]){
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(true);
        }
        else{
            jCheckBox1.setSelected(true);
            jCheckBox2.setSelected(false);
        }        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String estacion = (String)jComboBox1.getSelectedItem();
        int est = (Integer)grafo.thEstaciones.get(estacion);
        
        if (jCheckBox1.isSelected()){
            grafo.desactivadas[est] = false;
            for(int i=0;i<grafo.grafo.length;i++){
                grafo.grafo[est][i] = grafo.grafoEstatico[est][i];
                grafo.grafo[i][est] = grafo.grafoEstatico[i][est];
            }
        }
        if (jCheckBox2.isSelected()){
            grafo.desactivadas[est] = true;
            for(int i=0;i<grafo.grafo.length;i++){
                grafo.grafo[est][i] = 0;
                grafo.grafo[i][est] = 0;
            }            
        }        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new gesparadas().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
