/*
 * Registro.java
 *
 * Created on 27 de abril de 2007, 0:31
 */

package Metropolitano;

/**
 *
 * @author  Antonio
 */
public class Registro extends javax.swing.JFrame {
    private gesusuarios ges;
    /** Creates new form Registro */
    public Registro() {
        initComponents();
        this.ges = null;
    }
    public Registro(gesusuarios ges) {
        initComponents();
        this.ges = ges;
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDesktopPane2.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE USUARIOS");
        jLabel1.setBounds(130, 30, 160, 14);
        jDesktopPane2.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Nombre");
        jLabel2.setBounds(70, 60, 60, 20);
        jDesktopPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Apellido1");
        jLabel3.setBounds(70, 80, 70, 20);
        jDesktopPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Apellido2");
        jLabel4.setBounds(70, 100, 60, 20);
        jDesktopPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Email");
        jLabel5.setBounds(70, 120, 60, 20);
        jDesktopPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("DNI");
        jLabel6.setBounds(70, 140, 60, 20);
        jDesktopPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Usuario");
        jLabel7.setBounds(70, 160, 70, 20);
        jDesktopPane2.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("Password");
        jLabel8.setBounds(70, 180, 80, 20);
        jDesktopPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setText("Repetir Password");
        jLabel9.setBounds(70, 200, 110, 20);
        jDesktopPane2.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.setBounds(180, 60, 90, 20);
        jDesktopPane2.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField2.setBounds(180, 80, 90, 20);
        jDesktopPane2.add(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField3.setBounds(180, 100, 90, 20);
        jDesktopPane2.add(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField4.setBounds(180, 120, 90, 20);
        jDesktopPane2.add(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField5.setBounds(180, 140, 90, 20);
        jDesktopPane2.add(jTextField5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField6.setBounds(180, 160, 90, 20);
        jDesktopPane2.add(jTextField6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField7.setBounds(180, 180, 90, 20);
        jDesktopPane2.add(jTextField7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton1.setBounds(180, 240, 80, 23);
        jDesktopPane2.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField8.setBounds(180, 200, 90, 20);
        jDesktopPane2.add(jTextField8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDesktopPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String Nombre = jTextField1.getText();
        String Apellido1 = jTextField2.getText();
        String Apellido2 = jTextField3.getText();
        String Email = jTextField4.getText();
        String DNI = jTextField5.getText();
        String Usuario = jTextField6.getText();
        String Password = jTextField7.getText();
        String RPassword = jTextField8.getText();
        
        if (Nombre.equals("") || Apellido1.equals("") || Apellido2.equals("") || Email.equals("") || DNI.equals("") || Usuario.equals("") || Password.equals("") || RPassword.equals("")){
            Error1 error1 = new Error1();
            error1.setVisible(true);
        }
        else{
            if(!Password.equals(RPassword)) {
                Error2 err2 = new Error2();
                err2.setVisible(true);
            }
            else{
                BasesDatos bd = new BasesDatos();
                bd.abrirConexion();
                Integer dni  = Integer.valueOf(DNI);
                if(bd.obtenerDatosTabla(dni)) {
                    Error3 err = new Error3();
                    err.setVisible(true);
                }
                else {
                    bd.insertar(dni,Nombre,Apellido1,Apellido2,Email, Usuario,Password,false);
                    
                    this.dispose();
                }   
                bd.cerrarConexion();
            }
        }
        if(ges != null) ges.pintar();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
    
}
