/*
 * VentGestTablaSudokus.java
 *
 * Created on 1 de junio de 2007, 16:46
 */

package Menu;
import Gestion.BBDD;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author  Alberto
 */
public class VentGestTablaSudokus extends javax.swing.JPanel {
 private VentRaiz vRaiz;     
    /** Creates new form VentGestTablaSudokus */
    public VentGestTablaSudokus(VentRaiz vRaiz) {
        initComponents();
        this.vRaiz = vRaiz;
        pintar();        
    }
    
    public void pintar(){
        BBDD bd = new BBDD();
        bd.abrirConexion();


            
            ArrayList sudokus = new ArrayList();
            sudokus = bd.obtenerTsudokuss();

            DefaultTableModel model = new DefaultTableModel();
            model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            for(int i=0;i<sudokus.size();i++){
                ArrayList sudoku = new ArrayList();
                sudoku = (ArrayList) sudokus.get(i);                
                
                model.addRow(new Object[]{});
                jTable1.setValueAt(false,i,0);
                jTable1.setValueAt(sudoku.get(0),i,1);
                jTable1.setValueAt(sudoku.get(1),i,2);
                jTable1.setValueAt(sudoku.get(2),i,3);          
            }

            bd.cerrarConexion();
    }        
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jDesktopPane1.setBackground(new java.awt.Color(212, 208, 200));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14));
        jLabel1.setText("Administrar Sudokus");
        jLabel1.setBounds(120, 10, 170, -1);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Eliminar", "Identificador", "Nombre", "Dificultad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(10, 50, 380, 190);
        jDesktopPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton1.setBounds(155, 250, 90, 30);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        for(int i=0; i<jTable1.getRowCount();i++){
            Boolean eliminar = (Boolean)jTable1.getValueAt(i,0);
            
            if(eliminar){
                BBDD bd = new BBDD();
                bd.abrirConexion();
                String ID = (String) jTable1.getValueAt(i,1);   
                Integer id  = Integer.valueOf(ID);                
                bd.borrarTsudokus(id);
                bd.cerrarConexion();
            } else{
                BBDD bd = new BBDD();
                bd.abrirConexion();
                String ID = (String) jTable1.getValueAt(i,1);   
                Integer id  = Integer.valueOf(ID);
                bd.modificarTsudokus("Nombre",(String)jTable1.getValueAt(i,2),id);
                
                String Dificultad = (String) jTable1.getValueAt(i,3);   
                Integer dif  = Integer.valueOf(Dificultad);                     
                bd.modificarTsudokus("Dificultad",dif,id);    
                bd.cerrarConexion();
            }
            
        }
        VentAdmin vAdmin=new VentAdmin(vRaiz);
            vAdmin.setVisible(true);
            vAdmin.setSize(2000,2000);
            vRaiz.remove(this);
            vRaiz.add(vAdmin);
            vRaiz.pack();        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
