/*
 * VentVerComp.java
 *
 * Created on 1 de junio de 2007, 14:10
 */

package Menu;
import Gestion.BBDD;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
/**
 *
 * @author  Alberto
 */
public class VentVerComp extends javax.swing.JPanel {
    private VentRaiz vRaiz;    
    /**
     * Creates new form VentVerComp
     */
    public VentVerComp(VentRaiz vRaiz) {
        initComponents();
        this.vRaiz = vRaiz;
        
        pintar();
        
    }
    
    private void pintar(){
        BBDD bd = new BBDD();
        bd.abrirConexion();
        
        ArrayList competiciones = new ArrayList();
        competiciones = bd.obtenerCompeticiones(vRaiz.DNI);            

        DefaultTableModel model = new DefaultTableModel();
            model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
           
            for(int i=0;i<competiciones.size();i++){
                model.addRow(new Object[]{});                
                
                ArrayList competicion= new ArrayList();
                competicion = (ArrayList)competiciones.get(i);
                jTable1.setValueAt(competicion.get(0),i,0);                 
                jTable1.setValueAt(competicion.get(1),i,1);
                
                int restantes = 0;
                for(int j=2;j<6;j++) 
                    if (!(Boolean)competicion.get(j)) 
                        restantes++;
                jTable1.setValueAt(restantes,i,2);
                
                String Ganador = "";
                
                if(restantes == 0) {
                    Ganador = buscarganador((Integer)competicion.get(0));
                }

                jTable1.setValueAt(Ganador,i,3);                
            }
        bd.cerrarConexion();         
    }
    
    private String buscarganador(int competicion){
        BBDD bd = new BBDD();
        bd.abrirConexion();        
        
        ArrayList estadocompeticion = new ArrayList();
        estadocompeticion = bd.obtenerGanador(competicion);
        
        int i=0;
        boolean terminada = true;
        int maximo = 0;
        int DNImaximo = 0;
        while (terminada && i<estadocompeticion.size()){
            ArrayList participante = new ArrayList();
            participante = (ArrayList) estadocompeticion.get(i);
            
            if(maximo<=(Integer)participante.get(2)){
                maximo = (Integer)participante.get(2);
                DNImaximo = (Integer)participante.get(1);
            }
            
            for(int j=3;j<7;j++){
                terminada = terminada && (Boolean)participante.get(j);
            }
            i++;
        }
        
        if (!terminada) return "";
        else{
            return (String) bd.obtenerDatosTusuarios(DNImaximo,"Usuario");
            
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jDesktopPane1.setBackground(new java.awt.Color(212, 208, 200));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14));
        jLabel1.setText("Competiciones");
        jLabel1.setBounds(130, 30, 140, 21);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Competición", "Puntos Acumulados", "Sudokus Restantes", "Ganador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(10, 60, 380, 170);
        jDesktopPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton1.setBounds(150, 250, 100, 30);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            VentMenu vMenu=new VentMenu(vRaiz);
            vMenu.setVisible(true);
            vMenu.setSize(2000,2000);
            vRaiz.remove(this);
            vRaiz.add(vMenu);
            vRaiz.pack();        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
