/*
 * VentReg.java
 *
 * Created on 1 de junio de 2007, 13:08
 */

package Menu;
import Gestion.BBDD;
/**
 *
 * @author  Alberto
 */
public class VentReg extends javax.swing.JPanel {
    private VentRaiz vRaiz;
    /**
     * Creates new form VentReg
     */
    public VentReg(VentRaiz vRaiz) {
        initComponents();
        this.vRaiz = vRaiz;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNb = new javax.swing.JTextField();
        jTextFieldAp1 = new javax.swing.JTextField();
        jTextFieldAp2 = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldUser = new javax.swing.JTextField();
        jTextFieldPass = new javax.swing.JTextField();
        jTextFieldPassConf = new javax.swing.JTextField();
        jButtonRegistro = new javax.swing.JButton();

        jDesktopPane1.setBackground(new java.awt.Color(212, 208, 200));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14));
        jLabel1.setText("Registro de usuario");
        jLabel1.setBounds(120, 30, 160, 21);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Nombre ");
        jLabel2.setBounds(70, 60, 110, 20);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Apellido 1 ");
        jLabel3.setBounds(70, 80, 110, 20);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Apellido 2");
        jLabel4.setBounds(70, 100, 110, 20);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Email");
        jLabel5.setBounds(70, 120, 110, 20);
        jDesktopPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("DNI");
        jLabel6.setBounds(70, 140, 110, 20);
        jDesktopPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Usuario");
        jLabel7.setBounds(70, 170, 110, 20);
        jDesktopPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("Password");
        jLabel8.setBounds(70, 190, 110, 20);
        jDesktopPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setText("Confirmar password");
        jLabel9.setBounds(70, 210, 110, 20);
        jDesktopPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldNb.setBounds(180, 60, 140, 20);
        jDesktopPane1.add(jTextFieldNb, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldAp1.setBounds(180, 80, 140, 20);
        jDesktopPane1.add(jTextFieldAp1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldAp2.setBounds(180, 100, 140, 20);
        jDesktopPane1.add(jTextFieldAp2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldEmail.setBounds(180, 120, 140, 20);
        jDesktopPane1.add(jTextFieldEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldDNI.setBounds(180, 140, 140, 20);
        jDesktopPane1.add(jTextFieldDNI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldUser.setBounds(180, 170, 140, 20);
        jDesktopPane1.add(jTextFieldUser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldPass.setBounds(180, 190, 140, 20);
        jDesktopPane1.add(jTextFieldPass, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldPassConf.setBounds(180, 210, 140, 20);
        jDesktopPane1.add(jTextFieldPassConf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonRegistro.setText("Registrar");
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });

        jButtonRegistro.setBounds(150, 250, 100, 30);
        jDesktopPane1.add(jButtonRegistro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 400, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //******************************************//
    //*** Métodos auxiliares *******************//
    //******************************************//
    private void borrarFormulario() {
        //***** borrarFormulario() **************************************************//
        //*** borra los jTextField del formulario                                 ***//
        //***************************************************************************//
        jTextFieldNb.setText("");
        jTextFieldAp1.setText("");
        jTextFieldAp2.setText("");
        jTextFieldDNI.setText("");
        jTextFieldEmail.setText("");
        jTextFieldUser.setText("");
        jTextFieldPass.setText("");
        jTextFieldPassConf.setText("");
    }
    private boolean campoErroneo() {
        //***** campoErroneo() ******************************************************//
        //*** Devuelve true si los datos introducidos en el formulario corres-    ***//
        //*** ponden a algún usuario registrado o el email está mal puesto. De-   ***//
        //*** vuelve false en otro caso.                                          ***//
        //***************************************************************************//
        String Nombre = jTextFieldNb.getText();
        String Apellido1 = jTextFieldAp1.getText();
        String Apellido2 = jTextFieldAp2.getText();
        String Email = jTextFieldEmail.getText();
        String DNI = jTextFieldDNI.getText();
        String Usuario = jTextFieldUser.getText();
        String Password = jTextFieldPass.getText();
        String RPassword = jTextFieldPassConf.getText();
        
        BBDD bd = new BBDD();
        bd.abrirConexion();
        
        
        
        if (Nombre.equals("") || Apellido1.equals("") || Apellido2.equals("") || Email.equals("") || DNI.equals("") || Usuario.equals("") || Password.equals("") || RPassword.equals(""))
            return true;  // Devuelve true si el email es incorrecto o el usuario introducido estaba en la base de datos
        else{
            Integer dni  = Integer.valueOf(DNI);
            
            
            if(bd.compruebaUsuario(Usuario) || bd.compruebaDNI(dni) || emailIncorrecto() || !Password.equals(RPassword))
                return true;  // Devuelve false si el email es correcto y el usuario introducido no estaba en la base de datos
            else return false;
        }
        
        
    }
    private boolean emailIncorrecto() {
        //***** emailIncorrecto() ***************************************************//
        //*** Comprueba si el email metido en el jTextFieldEmail es incorrecto.   ***//
        //*** Si es incorrecto devuelve true. En caso contrario devuelve false.   ***//
        //***************************************************************************//
        String email=jTextFieldEmail.getText();
        if (email=="")
            return true;
        else {
            int numArrobas=0;
            int numPuntos=0;
            int posArroba=0;
            int posPunto=0;
            String arroba="@";
            String punto=".";
            for (int i=0; i<email.length(); i++) {
                String letra=email.substring(i,i+1);
                if (letra.equals(arroba)) {
                    numArrobas++;
                    posArroba=i;
                } else if (letra.equals(punto)) {
                    numPuntos++;
                    posPunto=i;
                }
            }
            int longitud=email.length();
            if (numArrobas==1 && numPuntos==1 && posArroba!=-1 && posPunto!=-1 && posArroba>0 && posPunto<longitud-1 && posArroba+1<posPunto)
                return false;  // Devuelve false, indicando que el email no es incorrecto
            else
                return true;  // Devuelve true, indicando que el email es incorrecto
        }
    }
    
    
    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
//***** Botón Registrar *****************************************************//
        //*** Registra un usuario en la base de datos según los datos introduci- ***//
        //*** dos y te devuelve a la pantalla de login. Si ya existía el usuario ***//
        //*** o el mail está mal puesto borra los jTextField del formulario.     ***//
        //***************************************************************************//
        if (campoErroneo())
            borrarFormulario();
        else {
            
            String Nombre = jTextFieldNb.getText();
            String Apellido1 = jTextFieldAp1.getText();
            String Apellido2 = jTextFieldAp2.getText();
            String Email = jTextFieldEmail.getText();
            String DNI = jTextFieldDNI.getText();
            String Usuario = jTextFieldUser.getText();
            String Password = jTextFieldPass.getText();
            String RPassword = jTextFieldPassConf.getText();
            
            BBDD bd = new BBDD();
            bd.abrirConexion();
            Integer dni  = Integer.valueOf(DNI);
            bd.insertarTusuarios(dni,Nombre,Apellido1,Apellido2,Email,Usuario,Password,"Usuario",0);
            bd.cerrarConexion();
            VentLogin vLogin=new VentLogin(vRaiz);
            vLogin.setVisible(true);
            vLogin.setSize(2000,2000);
            vRaiz.remove(this);  // ERROR 1: No deja eliminar
            vRaiz.add(vLogin);
            vRaiz.pack();
        }
    }//GEN-LAST:event_jButtonRegistroActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldAp1;
    private javax.swing.JTextField jTextFieldAp2;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNb;
    private javax.swing.JTextField jTextFieldPass;
    private javax.swing.JTextField jTextFieldPassConf;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
    
}
