/*
 * VentJugarComp.java
 *
 * Created on 1 de junio de 2007, 13:52
 */

package Menu;
import Gestion.BBDD;
import java.util.ArrayList;
/**
 *
 * @author  Alberto
 */
public class VentJugarComp extends javax.swing.JPanel {
    private VentRaiz vRaiz;
    /** Creates new form VentJugarComp */
    public VentJugarComp(VentRaiz vRaiz) {
        initComponents();
        this.vRaiz = vRaiz;
        
        
        
        listaCompeticiones();
        
    }
    
    private void listaCompeticiones(){
        BBDD bd = new BBDD();
        bd.abrirConexion();
        ArrayList listacompeticiones = new ArrayList();
        listacompeticiones = bd.obtenerCompeticiones(vRaiz.DNI);
        bd.cerrarConexion();
        for(int i=0;i<listacompeticiones.size();i++){
            ArrayList competicion = new ArrayList();
            competicion = (ArrayList)listacompeticiones.get(i);
            boolean terminada = true;
            for(int j=2;j<6;j++)
                terminada = terminada && (Boolean)competicion.get(j);
            if(!terminada) jComboBox1.addItem(competicion.get(0));
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jDesktopPane1.setBackground(new java.awt.Color(212, 208, 200));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14));
        jLabel1.setText("Jugar Competici\u00f3n");
        jLabel1.setBounds(130, 50, 150, 21);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.setBounds(140, 110, 110, 22);
        jDesktopPane1.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton1.setBounds(145, 183, 100, 30);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
            Integer idcompeticion = (Integer)jComboBox1.getSelectedItem();

        VentSudokuComp vPpal=new VentSudokuComp(vRaiz,idcompeticion);
        vPpal.setVisible(true);
        vPpal.setSize(2000,2000);
        vRaiz.remove(this);
        vRaiz.add(vPpal);
        vRaiz.pack();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
