/*
 * VentCrearComp.java
 *
 * Created on 31 de mayo de 2007, 23:45
 */

package Menu;
import Gestion.BBDD;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
/**
 *
 * @author  Alberto
 */
public class VentCrearComp extends javax.swing.JPanel {
     private VentRaiz vRaiz;
    /** Creates new form VentCrearComp */
    public VentCrearComp(VentRaiz vRaiz) {
        initComponents();
        this.vRaiz = vRaiz;
        
        listaSudokus();
        listaUsuarios();
        
    }
    
    private void listaSudokus(){
            BBDD bd = new BBDD();
            bd.abrirConexion();           
            
            
            ArrayList listasudokus = new ArrayList();
            listasudokus = bd.obtenerTsudokus();       
            
            for(int i=0;i<listasudokus.size();i++){
                jComboBox1.addItem(listasudokus.get(i));
                jComboBox2.addItem(listasudokus.get(i));
                jComboBox3.addItem(listasudokus.get(i));
                jComboBox4.addItem(listasudokus.get(i));
            }
            
            
            bd.cerrarConexion();            
    }
    
    private void listaUsuarios(){
            BBDD bd = new BBDD();
            bd.abrirConexion(); 
            
            ArrayList listausuarios = new ArrayList();
            listausuarios = bd.obtenerTusuarios();            

            
            DefaultListModel model = new DefaultListModel();
            //model = (DefaultListModel) jList1.getModel();
            //model.setSize(listausuarios.size());          
            for(int i=0;i<listausuarios.size();i++){
                model.addElement(listausuarios.get(i));
            }            
            jList1.setModel(model);
            bd.cerrarConexion();            
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        jDesktopPane1.setBackground(new java.awt.Color(212, 208, 200));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14));
        jLabel1.setText("Crear Competici\u00f3n");
        jLabel1.setBounds(120, 30, 150, 17);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Tiempo m\u00e1ximo");
        jLabel2.setBounds(50, 60, 110, 14);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Sudoku 1");
        jLabel3.setBounds(50, 90, 110, 14);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Sudoku 2");
        jLabel4.setBounds(54, 110, 100, 14);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Sudoku 3");
        jLabel5.setBounds(54, 130, 100, 14);
        jDesktopPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("Sudoku 4");
        jLabel6.setBounds(54, 150, 100, 14);
        jDesktopPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Jugadores");
        jLabel7.setBounds(50, 200, 100, 14);
        jDesktopPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.setText("0");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTextField1.setBounds(170, 60, 59, 20);
        jDesktopPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.setBounds(170, 90, 100, 22);
        jDesktopPane1.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox2.setBounds(170, 110, 100, 22);
        jDesktopPane1.add(jComboBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox3.setBounds(170, 130, 100, 22);
        jDesktopPane1.add(jComboBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox4.setBounds(170, 150, 100, 22);
        jDesktopPane1.add(jComboBox4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setViewportView(jList1);

        jScrollPane1.setBounds(170, 180, 100, 60);
        jDesktopPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton1.setBounds(170, 250, 100, 30);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
      char caracter = evt.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != java.awt.event.KeyEvent.VK_BACK_SPACE))
      {
         evt.consume();  // ignorar el evento de teclado
      }
    }//GEN-LAST:event_jTextField1KeyTyped

    
    private boolean valoresCorrectos(){
        return(tiempoOK() && sudokusOK() && jugadoresOK());
    }
    
    private boolean tiempoOK(){
        String Tiempo = jTextField1.getText();  
        if (Tiempo.equals("")) return false;
        else{
            Integer tiempo  = Integer.valueOf(Tiempo);
            return tiempo > 0;
        }
    }
    
    private boolean sudokusOK(){
        int S1 = jComboBox1.getSelectedIndex();
        int S2 = jComboBox2.getSelectedIndex();
        int S3 = jComboBox3.getSelectedIndex();
        int S4 = jComboBox4.getSelectedIndex();
        
        return ((S1 != S2) && (S1 != S3) && (S1 != S4) && (S2 != S3) && (S2 != S4) && (S3 != S4) );
    }
    
    private boolean jugadoresOK(){
        return (jList1.getSelectedIndex() != -1);
    }
    
    private void borrarFormulario(){
        jTextField1.setText("0");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jList1.setSelectedIndex(-1);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (valoresCorrectos()){
            BBDD bd = new BBDD();
            bd.abrirConexion();            
            
            
            String Tiempo = jTextField1.getText();         
            Integer tiempo  = Integer.valueOf(Tiempo);            
            
            String S1 = (String)jComboBox1.getSelectedItem();
            int Sudoku1 = bd.obtenerIDTsudokus(S1);
            String S2 = (String)jComboBox2.getSelectedItem();
            int Sudoku2 = bd.obtenerIDTsudokus(S2);            
            String S3 = (String)jComboBox3.getSelectedItem();
            int Sudoku3 = bd.obtenerIDTsudokus(S3);            
            String S4 = (String)jComboBox4.getSelectedItem();
            int Sudoku4 = bd.obtenerIDTsudokus(S4);            
            

            int id = bd.maxCompeticiones() + 1;
            
            bd.insertarTcompeticion(id,Sudoku1,Sudoku2,Sudoku3,Sudoku4,tiempo);
            
            Object usuarios[] = new Object[jList1.getSelectedIndices().length];
            usuarios = jList1.getSelectedValues();
            
            
            for (int i=0; i<usuarios.length;i++){   
                String u = (String)usuarios[i];
                int dni = bd.obtenerDNI(u);                
                bd.insertarTestadocompeticion(id,dni,0,false,false,false,false);
            }
            
            bd.cerrarConexion();
            
            VentMenu vMenu=new VentMenu(vRaiz);
            vMenu.setVisible(true);
            vMenu.setSize(2000,2000);
            vRaiz.remove(this);
            vRaiz.add(vMenu);
            vRaiz.pack();            
            
        }
        else borrarFormulario();
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
